### ISSUE TITLE
How can I format the result having comma instead of the period as the decimal point?

### ISSUE THREAD

**Issue by piiskop** [graphdr/formatdown#6]

**Comment by graphdr** [comment]
That will require a new argument.  I’m working on it now. Will let you know when I’ve updated the development version.  

Thanks!

**Comment by graphdr** [comment]
The development version 0.1.3.9001 now supports a comma as the decimal marker. You can set it globally using the new `formatdown_options()` function or you can set it in an individual function call. 

At the same time, the main formatting functions have been updated with new names (and new options) and the old names are deprecated. It turns out that all the numerical formatting functions were actually special cases of a more general function, now called `format_numbers()`.

**Comment by graphdr** [comment]
Version 0.1.4 has posted to CRAN and includes the option for assigning a comma as the decimal marker.

**Comment by graphdr** [comment]
Version 0.1.4 has posted to CRAN and includes the option for assigning a comma as the decimal marker.
